- Views/js/designer.js
Instead of checking on full name (id=="colour"), it now checks on a prefix (id starts with "colour"). Needed for visualizations that may define more than one colour (for example stacked).
Without this change, PR #444 (colour configuration in Stacked visualization) doesn't work inside dashboards.
> Allow more than one option to be a colour picker

- Views/js/designer.js
This adds key bindings when on the dashboard editor so that you can move items around with the arrow keys. Items move by 1 grid size unit in whichever direction of arrow you press.
> Add key bindings to move things around the dashboard editor

- Views/js/designer.js
This fixes the issue that @Paul-Reed noticed, whereby you can move elements off the screen with the arrow keys.
I've implemented it in the same way as the mouse events work. That is, you can't move the centre of the elements off the left, top or right of the page. And when you move the element off the bottom of the page, the page height simply changes to accommodate the element with an extra `grid_size` amount as padding.
> Ensure that the element doesn't move off the page when using arrow keys

- widget/dial/dial_render.js
Me again!
I noticed 2 issues with the `dial` widget:
1. <img width="178" alt="screen shot 2016-09-08 at 12 10 15" src="https://cloud.githubusercontent.com/assets/753010/18348604/38f1de5c-75c4-11e6-9c55-76f0948e9267.png">
Umm, that doesn't look right. The start limit is wrong. It should say `-2000` here. Notice that the needle is in the right position, it's just the limit that's wrong.
2. <img width="185" alt="screen shot 2016-09-08 at 12 10 30" src="https://cloud.githubusercontent.com/assets/753010/18348605/38f6c110-75c4-11e6-8f63-8332d2a418c0.png">
Also not right. When the dial is of a type where it's not zero at the far left, the needle can overshoot on the left.
This PR fixes both of those issues, and adds some documentation in the code to help understand the `needle` calculation. I …
> Fix dial widget start limit issues

- Views/js/designer.js
@Paul-Reed - sorry about this... I just noticed that with my delete key binding, you can end up deleting the selected element while you're configuring it, if you press backspace / delete while in a text box. This commit fixes it.
> Don't do the delete if you're inside an input or textarea

- Views/js/render.js
This fixes it so that with the read key passed as the `apikey` parameter in the URL query, you can see a dashboard. Without this fix, widgets are blank because the `list` query doesn't pass the API key, so you don't get any results back.
> Add apikey to list query, so that you can view dashboards with the readkey

- widget/led/led_render.js
As title. This enabled the LED widget to scale with the size of the widget itself. I've carefully crafted it such that if you have an existing widget of the standard size (i.e. haven't resized it) then it'll appear just as it did before this change.
> Make the LED widget scale with the size of the widget

- Views/js/designer.js
This change means that if you move something left 5 times, then the undo states are all squashed into one. This is more natural. Similarly if you move things forward or backward multiple times, it's just one undo state.
> Merge undo states if it's the same action multiple times in a row

- Views/dashboard_edit_view.php
See #31. There was a problem where if you saved when the content hadn't actually changed, then there was an error. Of course it's not actually an error, but rather the content hasn't changed, so there's nothing to save. This could happen if you moved something to the left and then back again. With undo/redo now it's more likely to happen, so important to fix. This fixes it.
Fixes #31.
> Fix saving when the content hasn't actually changed

- Views/js/designer.js
We had an issue where if you made some changes, then saved, then did an undo or redo, you couldn't save until you made another change. This was because undo and redo weren't setting the modified state. This fixes that.
Fixes #34.
> Make undo and redo set modified state correctly

- Views/dashboard_edit_view.php
- Views/dashboard_menu.php
- Views/js/designer.js
Found issue with elements within the div draggable too. Reworked js code and now only the palette itself is draggable.
- added submenu icons "daschboard config and preview into the palette.
- removed the icons from the submenu and ensured that the submenu is not visible anymore in edit mode
- styled the buttons to be the same height as the others are (still need to figure out new icons or icon name combination for later or adding additional small icons there like instead big buttons for undo/redo, backw/forw.
- added auto grow to the div so the palette will get bigger as soon as a element has been selected.
- added border to the palette to make it more visible in case of grey dashboard elements
> Toolbox js reworked

- Views/dashboard_edit_view.php
This changes the palette to use jQuery instead of normal JS. Just a bit nicer and more portable.
It also fixes an issue where if you dragged while clicking on one of the buttons, it moved the palette.
> Use jQuery instead of normal JS

- Views/dashboard_edit_view.php
Added fixed values for stopping the palette from moving of screen on the left and top.
Moving it to the right and down still works and will create a scrollbar. The palette is therefore always reachable.
> Fixing moving Palette outside of upper and left DIV limits

- widget/bar/bar_render.js
For example, to correct;
9.00 = 3 digits
10.00 = 4 digits
11.0 = 3 digits
> Change precision rules to maintain digit count

- widget/humidex/humidex_render.js
Add double quotes in === comparison otherwise Fahrenheit to celsius conversion is ignored.
Celsius to Farhenheit conversion supressed because the Humidex is based from a temperature in °C and the scale is about 29-60
> fix issue and Fahrenheit conversion deleted

- widget/led/led_render.js
obsolete and unused draw_binary_led suppressed
add an option with 2 choices of style :
actual style with colour gradients
style without colour gradients in order to have a flat design (in fact function developed in the past for IE8, but probably this have never worked for this browser ...)
> led widget : new style

- widget/dewpoint/dewpoint_render.js
- widget/feedvalue/feedvalue_render.js
- widget/frostpoint/frostpoint_render.js
- widget/heatindex/heatindex_render.js
- widget/humidex/humidex_render.js
add consistency across the widgets, and remove the non-significant digits when decimals are set as automatic
> Decimals fix

- widget/bar/bar_render.js
- widget/dial/dial_render.js
- widget/thermometer/thermometer_render.js
Add z-index property in order to be sure that tooltip is visible when the tooltip is outside the area of the associated widget
> Tooltip improvement

- widget/bar/bar_render.js
- widget/bar/bar_widget.php
- widget/dial/dial_render.js
- widget/dial/dial_widget.php
- widget/feedtime/feedtime_render.js
- widget/feedtime/feedtime_widget.php
- widget/feedvalue/feedvalue_render.js
- widget/feedvalue/feedvalue_widget.php
Hi all, this is my first pull request to th EmonCMS project.
For I time, I had the problem of not noticing when a device stopped sending data, because the widgets continued to display the feed value, even if it wasn't updated.
The 3 widgets I use commonly are FeedValue, Dial and Bar, so I edited only these.
I have added a new parameter in the config options of each widget, called timeout. After the seconds specified in timeout without feed update, the widget shows "TO Error" in the numeric display and the Dial or the Bar goes to 0.
If 0 is specified in the timeout value, it never timeouts. If it is left empty, it timeouts to 60 seconds. I added this last feature for not changing all the dashboards I have.
I also added a new widget called FeedTime, which shows how old is a feed in seconds. …
> Added timeout in FeedValue, Dial and Bar and new Widget called FeedTime

- widget/feedtime/feedtime_render.js
Comma removed. Without this fix, widgets are not displayed in IE11 (works with firefox and Edge anyway)
> fix ie11 error

- Views/js/designer.js
By directly double clicking on a widget, the widget options popup appears.
> Add double click action on widget

- Views/js/designer.js
if the width and the height of the widget are greater than 125, the size of the boxes is set to 25
if the width and the height of the widget are greater than 75, the size of the boxes is set to 16
otherwise the size of the boxes is set to 8 (legacy size)
> dynamic size of box for resizing and moving of widget

- Views/js/designer.js
Before : 
text truncated
issue with color picker on FireFox 60.0.2
After : 
text no longer truncated : size increased for tags and font size decreased
color picker now correctly displayed on Firefox
> enlarge space for tags - color picker improvement

- widget/battery/battery_render.js
When timeout is reached, the value is replaced by an error message if timeout specified.
here are some screen captures concerning the behaviour :
when timeout is not reached :
when timeout is reached :
New options for the widget :
> battery widget timeout improvement

- widget/jgauge/jgauge_render.js
When timeout is reached, the value is replaced by an error message if timeout specified and the needle is not displayed
here are some screen captures concerning the behaviour :
when timeout is not reached :
when timeout is reached :
New options for the widget :
> management of timeout for jgauge

- widget/frostpoint/frostpoint_render.js
> frostpoint - aligment

- widget/feedtime/feedtime_render.js
> feedtime aligment

- widget/dewpoint/dewpoint_render.js
> dewpoint align option

- widget/heatindex/heatindex_render.js
> heatindex alignment

- widget/humidex/humidex_render.js
> humidex align

- Views/dashboard_view.php
To enable the bookmarks feature to name the dashboard correctly it requires a hidden page title. this pull request does that work
> added hidden title to allow bookmarks to name the link

- dashboard_menu.php
- dashboard_model.php
modified model to supply dashboard id
fix #214 
the menu item now responds to any one of these urls:
- dashboard/view?id=[dashboard id]
- dashboard/edit?id=[dashboard id]
- dashboard/view/[dashboard alias]
> used dashboard id to build edit and view urls

- Views/dashboard_config.php
- Views/dashboard_view.php
- dashboard_controller.php
- dashboard_model.php
- dashboard_schema.php
added new checkbox to allow user to set property
added js to alter view template if property set
added new database field. **Need to update database** schema to enable this feature correctly
` EmonCMS->Admin->Update...->Update Database Only`
[screenshot of new dashboard option]
[screenshot of dashboard edit]
[screenshot of same dashboard being viewed without menus showing]
> added new property to dashboard sql table "fullscreen"

- widget/feedvalue/feedvalue_render.js
Add options in the dialog box concerning settings of the item (feedvalue widget): 
When thresholds 1 and 2 are not specified (empty), the default color is applied.
Otherwise, the color of the text is conditionned by colors specified for the 3 ranges and thresholds
> Add conditional color text

- Views/dashboard_edit_view.php
- dashboard_model.php
added some js translations
added check for nbsp and added it back after xss filter
using async function to save dashboard content
fix #171 
[screenshot of 2 tests causing errors - now don't cause errors]
> checked for html characters in model

- widget/battery/battery_render.js
Add the ability to define the number of blocks within the battery : 
For backward compatibility : default value is 5
> Add blocks feature

- dashboard_model.php
Avoid 'Undefined variable' when saving if php-mbstring is not installed.
In turn this notice is sent to the browser causing a JSON parse error.
> Fix for 'Undefined variable' on save.
