widget/curl/curl_render.js
- Added Curl Widget
Very useful to create action buttons in the dashboards. The implementation of the widget was originally created by [brutzler](https://openenergymonitor.org/emon/node/6394). I have refined it a little bit more.
Screenshot of the widget in the dashboard:
Screenshot of the configuration panel:
It can be used to for remote activation of the desired devices or desired processes in Node-Red using http request.
=> Curl Widget

widget/curl/curl_render.js
Restored "confirm" option lost in the commit fb9e4f2feae4383806a501a28c811b87ca2cd059
=> Restored missing confirmation option

Views/dashboard_config.php, Views/dashboard_edit_view.php, Views/js/designer.js, dashboard_model.php, dashboard_schema.php
This adds an option to dashboard to set the grid size. I noticed that quite a few people have the problem where they want to change this. This enables you to change it.
=> Add a grid size option to dashboard

Views/dashboard_edit_view.php, Views/js/designer.js
This adds buttons to move the currently selected element forwards and backwards.
[As requested by @Paul-Reed ;-). But a really neat idea, which is highly useful!]
=> Add buttons to move elements forwards and backwards

Views/js/designer.js
As title. You can now press the backspace or delete key to delete items.
In this PR I also pull out the arrow key logic into a separate function. Gotta keep things sane in this file!
=> Add binding on the delete key to delete selected boxes

widget/feedvalue/feedvalue_render.js
=> Add an option to feedvalue to put the unit at the front

dashboard_langjs.php, widget/curl/curl_render.js
* Fixed mismatch translation tags
=> Fixed missmatch translation tags

Views/dashboard_edit_view.php, Views/js/designer.js
This adds undo/redo handling to the dashboard.
Looking for thought on this before it gets committed. The menu bar is getting a bit clogged with these and with the move forward/backward I added before. Maybe we should split into 2 rows? Have undo/redo and save on a second row?
=> Add undo/redo

Views/js/designer.js
This allows you to select multiple elements at the same time, so that you can move them around and bring them forwards, backwards.
Current limitation is that moving around is only supported by using the arrow keys. I want to support moving using the mouse, but it was more complicated. The way it is is still very useful though, IMO.
Would love some feedback on this.
=> Allow selecting multiple elements at once

Views/dashboard_edit_view.php, Views/js/designer.js
Added a floating toolbox to dashboard designer which has the option to move the toolbox within the dashboard. Arranged the buttons to fit into the box.
=> Toolbox upgarde

Views/dashboard_menu.php, Views/dashboard_view.php
Testing PB66's suggestion to completely remove the submenu bar. To achieve this I created a floating edit button with opacity to reduce the visibility. Using the Jquery code from Matt Galloway.
=> Removing submenu completely by adding floating edit icon

Views/dashboard_edit_view.php, Views/dashboard_view.php
Reworked edit button:
- Flat style
- Opacity 0.7 to help shine through stuff underneath
- Invisible DIV around for moving it it still occupies something
- Top right corner
Fixed double slashed when using the view button on the editor.
=> Edit button reworked and double slash fixed

widget/bar/bar_render.js
- Allow Title
- Allow Label colour
- Allow font selection
- made the value slightly smaller to make it fit better into the bar when graduations are off.
- should not break existing bar widgets. Tested locally but needs testing from others as well.
=> Bar Enhancements

widget/cylinder/cylinder_render.js
This brings in 2 things:
* Makes the cylinder draw to the height of the element, rather than a fixed height.
* Uses a gradient to draw the bit between the top and the bottom, rather than a self-made gradient using just 6 steps.
=> Cylinder improvements

widget/bar/bar_render.js, widget/dial/dial_render.js
=> Code refactoring

Views/dashboard_edit_view.php
Changed to onclick solution for the button fixing the not working state on IE and Firefox.
Tested on IE and Firefox and Edge and on EmonCMS in root and subfolder installations.
=> Fix button for IE and Firefox

locale/de_DE/LC_MESSAGES/messages.po
i've made some several corrections in german language context
=> little corrections for german language

dashboard_langjs.php, widget/battery/battery_render.js
=> Added Battery Widget

Views/dashboard_view.php
Dashboard edit icon only visible when logged in
=> Show dashboard edit icon only when logged in

widget/dial/dial_render.js
As I am using a BMP 180 sensor with Raspberry Pi and emoncms I have added a type that emulates a barometer in order to display a pressure
=> Add an option for the type

widget/feedvalue/feedvalue_render.js
add font style and font weight and optimize quality code
=> font and quality code improvements

widget/dial/dial_render.js
Add decimals and units position options and quality code improvement
=> additional options and quality code improvement

widget/cylinder/cylinder_render.js
optimization of the code
ability to set the number of decimals
choice of unit position (Back/Front/No display)
the widget now accepts temperature feeds in °F - conversion °F->°C is made in order to benefit from the correct temperature gradiant
=> update of cylinder widget

widget/cylinder/cylinder_render.js
=> Code optimization

Views/dashboard_edit_view.php, Views/dashboard_view.php, widget/isactivefeed/isactivefeed_widget.php
dashboard_edit_view.php and dashboard_view.php modified in order to go back to the previous version
isactivefeed_widget.php added in order to respect emonCMS architecture
=> Isactivefeed optimization

CHANGELOG.md
@glynhudson @TrystanLea - 
1) Addition of CHANGELOG.md to dashboard repo
2) Release of v1.0.0
Is this what you had in mind?
...a further thought is that a sticky 'read only' forum post could contain links to the respective github CHANGELOG.md files, ie dashboard, app, emoncms, etc...  so users could regularly click through and easily find the history of changes made.
Paul
=> Introduction to dashboard versioning

widget/sun/sun_render.js
add decimals, fontstyle, fontweight, position of unit options
optimization of the code
should not break existing widget - need to test
=> add options to the widget

widget/signal/signal_render.js
Add fontweight and fontstyle options
Auto resizing of the title
Prevents from a truncation of the graph
=> Add font options - other improvements

Views/dashboard_edit_view.php, Views/js/designer.js, Views/js/widgetlist.js, dashboard_langjs.php
=> Localization improvements

widget/bar/bar_render.js, widget/dial/dial_render.js, widget/thermometer/thermometer_render.js
Better management of tooltips divs
=> Tooltips improvements

Views/dashboard_edit_view.php, Views/dashboard_view.php, Views/js/designer.js, Views/js/widgetlist.js, dashboard_langjs.php, module.json, widget/bar/bar_render.js, widget/dial/dial_render.js, widget/thermometer/thermometer_render.js
See https://community.openenergymonitor.org/t/new-thermometer-widget-added-to-dashboard/4752/4
=> Merge Master > Stable to Fix IE11 browser errors

widget/thermometer/thermometer_render.js
As requested in PR #128 , a minimum option has been added
=> add min option for the widget

widget/thresholds/thresholds_render.js
* Create thresholds_render.js
This widget is similar to isactivefeed one in terms of "look and feel" but instead of indicating the status of update delay, this widget indicates if the feed value is above or below thresholds
* code optimization
=> Create threshold indicator widget (#134)

widget/bar/bar_render.js, widget/dial/dial_render.js, widget/thermometer/thermometer_render.js
code added in order to correctly update min and max values coming from virtual feeds
=> Better management of update

widget/bar/bar_render.js
hide feature but not bar when feed ids are invalid
=>  Fix for bar min/max feed value

widget/thermometer/thermometer_render.js
hide feature but not thermometer when feed ids are invalid
=>  Fix for thermometer min/max feed value

widget/dial/dial_render.js
hide feature but not dial when feed ids are invalid
=>  Fix for dial min/max feed value

widget/bar/bar_render.js, widget/dial/dial_render.js, widget/thermometer/thermometer_render.js
Hides min-max feature in the event of invalid feed (thib66)
=> min-max fix

Views/dashboard_edit_view.php, Views/dashboard_view.php
Before PR : 
After PR : 
Should be applied in conjunction with #346 of emoncms/emoncms repository
=> Localization vis options

Views/dashboard_config.php, dashboard, dashboard_model.php, dashboard_schema.php
fixes #160 
related to https://github.com/emoncms/emoncms/issues/246
=> made dashboard alias web friendly

widget/bar/bar_render.js
add customized error message.
fix bug when input has been updated with the same value.
before fix, error message was displayed
=> improvement of bar widget

widget/dial/dial_render.js
Add customized error message
Fix bug when input is updated with the same value
Before the fix, error message was displayed
now the needle is not displayed when timeout is reached
=> dial improvement

widget/thermometer/thermometer_render.js
Add customized error message
Fix bug when input is updated with the same value
Before the fix, error message was displayed
now the height of mercury for the value is not displayed when timeout is reached
=> thermometer improvement

dashboard_controller.php
=> Only require read key for listing dashboards in the JSON API

widget/signal/signal_render.js
When timeout is reached, the previous signal level is hidden and an error message can be displayed
=> signal render timeout improvement

widget/jgauge2/jgauge2_render.js
When timeout is reached, the value is replaced by an error message if timeout specified and the main needle is not displayed
here are some screen captures concerning the behaviour :
when timeout is not reached :
when timeout is reached :
=> jgauge2 timeout improvement

widget/feedvalue/feedvalue_render.js
Change order of options to be consistent with other based text widgets
=> feedvalue - reorder options

dashboard_model.php
Fix issue on regular expression containing an hyphen. Please see emoncms/emoncms#1180
=> Fix php7.3 regexp hyphen

Views/dashboard_edit_view.php, Views/dashboard_list.php, Views/dashboard_view.php, dashboard_menu.php
=> Dark sidebar

Views/dashboard_list.php
also corrected spelling of empty warning message
=> hide warning after addNew()

Views/dashboard_config.php, Views/dashboard_edit_view.php, Views/dashboard_view.php
related to emoncms pull request that adds a `emoncms.js` file.
https://github.com/emoncms/emoncms/pull/1404
=> used global js path variable

Views/dashboard_list.php
fix #233 
thanks @pb66 for the detailed explanation in #233
=> checked for empty value in dashboard alias

widget/isactivefeed/isactivefeed_render.js
Add new triangle options - similar to threshold widget
=> Add triangle options

dashboard_menu.php
=> localization of sidebar for dashboard module

widget/feedtimestamp/feedtimestamp_render.js
Add a new widget called feedtimestamp displaying the date and / or time of the last measure of a feed.
Several formats are proposed.
=> Feedtimestamp widget
